### ISSUE TITLE
Could I have the password for win7vs.7z

### ISSUE THREAD

**Issue by thenate217** [xDemonessx/dotfiles#1]

**Comment by xDemonessx** [comment]
You can find the theme here:

http://www.deviantart.com/art/Kombo-285108444
the license is here:
http://creativecommons.org/licenses/by-nd/3.0/
"No Derivatives — If you remix, transform, or build upon the material, you may not distribute the modified material."
Due to this license, and my respect for the original creator, I will not be redistributing a modified visual style.
